// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb6BzaX5ugCOqcRUml3dNVe6Ipa-Rb1zc',
    appId: '1:417485544914:web:37bbac48e65ba802e7bc0b',
    messagingSenderId: '417485544914',
    projectId: 'fir-chat-app-bd0ed',
    authDomain: 'fir-chat-app-bd0ed.firebaseapp.com',
    storageBucket: 'fir-chat-app-bd0ed.appspot.com',
    measurementId: 'G-3XZY4ZVKGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTPGg5unZRsrc51-b1tHSItU5z5_ueBE',
    appId: '1:300488105737:android:3143c6a561eaa6e6c2fdd8',
    messagingSenderId: '300488105737',
    projectId: 'fir-chatapp-4bee1',
    storageBucket: 'fir-chatapp-4bee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlN--siIKQkZRaUxgZo3zjXWO9g9yQjCA',
    appId: '1:300488105737:ios:d9f3d77a5e28357cc2fdd8',
    messagingSenderId: '300488105737',
    projectId: 'fir-chatapp-4bee1',
    storageBucket: 'fir-chatapp-4bee1.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTdX5TZy5o7GMQpmBavoIJcV4IAf5jQk',
    appId: '1:417485544914:ios:3faae5c17c046097e7bc0b',
    messagingSenderId: '417485544914',
    projectId: 'fir-chat-app-bd0ed',
    storageBucket: 'fir-chat-app-bd0ed.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb6BzaX5ugCOqcRUml3dNVe6Ipa-Rb1zc',
    appId: '1:417485544914:web:02a64a07ae34f8f4e7bc0b',
    messagingSenderId: '417485544914',
    projectId: 'fir-chat-app-bd0ed',
    authDomain: 'fir-chat-app-bd0ed.firebaseapp.com',
    storageBucket: 'fir-chat-app-bd0ed.appspot.com',
    measurementId: 'G-LZ10JP1B2H',
  );
}
